[
  ["purpura", "negro", "blanco"],
  ["purpura", "jean", "negro", "blanco"],
  ["purpura", "marino", "blanco"],
  ["purpura", "negro gastado", "blanco"],
  ["purpura", "marfil", "negro"],
  ["purpura", "negro"],
  ["purpura", "celeste", "blanco"],
  ["purpura", "gris claro", "blanco", "negro"],
  ["purpura", "gris oscuro", "negro"],
  ["purpura", "gris claro", "negro"],
  ["purpura", "gris claro", "blanco", "negro"],

  ["lila", "negro", "blanco"],
  ["lila", "jean", "negro", "blanco"],
  ["lila", "marino", "blanco"],
  ["lila", "negro gastado", "blanco"],
  ["lila", "marfil", "negro"],
  ["lila", "negro"],
  ["lila", "celeste", "blanco"],
  ["lila", "beige", "blanco"],
  ["lila", "gris oscuro", "negro"],
  ["lila", "gris oscuro", "blanco"],
  ["lila", "marino", "chocolate"],
  ["lila", "gris claro", "negro"],
  ["lila", "gris claro", "blanco", "negro"],
  ["lila", "negro gastado", "blanco"],
  ["lila", "aero", "blanco"],
  ["lila", "miltar", "blanco"],

  ["aero", "negro gastado", "blanco"],
  ["aero", "negro", "negro gastado"],
  ["aero", "marfil", "celeste", "blanco"],
  ["aero", "camel", "blanco"],
  ["aero", "gris claro", "blanco"],
  ["aero", "gris oscuro", "negro"],
  ["aero", "marfil", "blanco"],
  ["aero", "jean", "negro gastado"],
  ["aero", "blanco", "chocolate"],
  ["aero", "beige", "blanco"],
  ["aero", "blanco", "suela"],
  ["aero", "blanco", "chocolate"],
  ["aero", "celeste", "blanco", "negro"],

  ["marino", "blanco"],
  ["marino", "blanco", "suela"],
  ["marino", "blanco", "chocolate"],
  ["marino", "blanco", "cacahuate"],
  ["marino", "celeste", "blanco"],
  ["marino", "camel", "blanco"],
  ["marino", "beige", "suela"],
  ["marino", "marfil", "suela"],
  ["marino", "borgoña", "blanco"],
  ["marino", "militar", "blanco"],
  ["marino", "naranja", "blanco"],
  ["marino", "arena", "chocolate"],
  ["marino", "arena", "suela"],
  ["marino", "gris oscuro", "blanco"],
  ["marino", "gris claro", "negro"],
  ["marino", "jean", "gris claro", "cacahuate"],
  ["marino", "mostaza", "blanco"],
  ["marino", "mostaza", "jean", "blanco"],
  ["marino", "gris claro", "suela"],
  ["marino", "gris claro", "cacahuate"],
  ["marino", "rosa", "blanco"],
  ["marino", "ladrillo", "blanco"],
  ["marino", "blanco", "celeste", "cacahuate"],
  ["marino", "rojo", "blanco"],
  ["marino", "camel", "celeste"][("marino", "marfil", "suela")],
  ["marino", "marfil", "blanco", "negro"],
  ["marino", "gris claro", "blanco"],
  ["marino", "jean", "blanco"],
  ["marino", "jean", "suela"],
  ["marino", "celeste", "beige"],
  ["marino", "celeste", "suela"],
  ["marino", "militar", "negro"],

  ["francia", "jean", "blanco"],
  ["francia", "jean", "negro", "blanco"],
  ["francia", "beige", "blanco"],
  ["francia", "celeste", "blanco"],
  ["francia", "celeste", "mostaza", "gris claro"],
  ["francia", "negro gastado", "negro"],
  ["francia", "chocolate", "beige"],
  ["francia", "cacahuate", "gris oscuro"],
  ["francia", "camel", "blanco"],
  ["francia", "marfil", "suela", "gris oscuro"],

  ["celeste", "blanco"],
  ["celeste", "marino"],
  ["celeste", "jean", "amarrilo"],
  ["celeste", "gris claro", "arena"],
  ["celeste", "amarillo", "blanco"],
  ["celeste", "beige", "marino"],
  ["celeste", "negro", "blanco"],
  ["celeste", "marino", "suela"],
  ["celeste", "mostaza", "blanco"],
  ["celeste", "ladrillo", "marino"],
  ["celeste", "rosa", "blanco", "beige"],
  ["celeste", "negro gastado", "blanco"],
  ["celeste", "marfil", "cacahuate"],
  ["celeste", "camel", "blanco", " gris oscuro"],
  ["celeste", "borgoña", "negro"],
  ["celeste", "rojo", "blanco"],
  ["celeste", "beige", "negro", "blanco"],
  ["celeste", "gris oscuro", "gris claro"],
  ["celeste", "marino", "cacahuate"],
  ["celeste", "cacahuate", "negro"],
  ["celeste", "gris oscuro", "suela"],
  ["celeste", "beige", "blanco"],
  ["celeste", "ladrillo", "negro", "blanco"],
  ["celeste", "camel", "negro"],
  ["celeste", "jean", "blanco"],
  ["celeste", "beige", "chocolate"],
  ["celeste", "negro", "gris oscuro"],
  ["celeste", "francia", "blanco", "suela"],
  ["celeste", "negro", "suela"],
  ["celeste", "negro", "blanco"],
  ["celeste", "borgoña", "arena"],

  ["aguamarina", "marino", "suela", "blanco"],
  ["aguamarina","marino", "arena"],
  ["aguamarina", "marfil", "camel"],
  ["aguamarina","blanco", "arena"],
  ["aguamarina", "celeste", "blanco"],
  ["aguamarina","negro"],


  ["aguamarina","beige","camel"],
  ["aguamarina", "beige", "negro"],
  ["aguamarina","gris claro", "blanco"],
  ["aguamarina","jean", "blanco"],
  ["aguamarina", "negro gastado", "negro"],
  ["aguamarina",],
  ["aguamarina",],

  ["aguamarina",],
  ["aguamarina",],
  ["aguamarina",],
  ["aguamarina",],


  ["aguamarina",],
  ["aguamarina",],
  ["aguamarina",],
  ["aguamarina",],
  ["aguamarina",],
  ["aguamarina",],
  ["aguamarina",],
  ["aguamarina",],

];
